version: "3"
service:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
     - homes-app

  api-server:
    image: api-server
    ports:
      - "8000:8000"
    networks:
     - homes-app
    depends_on:
      - mongo
  
  mongo:
    image: mongo:3.6.19-xenial
    ports:
     - "27017:27017"
    networks:
     - homes-app
    volumes:
      - mongo-data:/data/db

networks:
  homes-app:
    driver: bridge
  
volumes:
  mongo-data:
    driver: local
